### ISSUE TITLE
可以再添加一个自动转发端口的功能

### ISSUE THREAD

**Issue by wkunzhi** [wrlu/FridaHooker#1]
可以再添加一个自动转发端口的功能

**Comment by wrlu** [comment]
1. PC端的frida做了自动转发端口功能，一般来说手机连上了有adb就可以直接用，不需要手动forward
2. adb forward这个命令是在PC端执行的，而本软件是在手机上，所以并不能直接完成这样的工作，除非我们直接和adbd这个进程通信。
