### ISSUE TITLE
Can't turn off

### ISSUE THREAD

**Issue by sterling0x1** [wrlu/FridaHooker#3]
Latest release switch is broken, wouldn't stay stay turned off.
Nice work btw, makes it simple to run and kill Frida server.

**Comment by wrlu** [comment]
Maybe the binding to port tcp:27042 is failed.
For using less root access, I cannot use ps command to know if frida-server is running or out.
So we try to bind the tcp port 27042 and if it fail we know the server is still running.
You can put the logcat output here for more information :)

**Comment by sterling0x1** [comment]
I forgot about this, sorry. Issue is fixed, I think I had fridaserver running from terminal and that might caused the issues.
