### ISSUE TITLE
建议把frida做成api,不要直接放到项目源码里面

### ISSUE THREAD

**Issue by dfaofeng** [wrlu/FridaHooker#7]
免得每次打包.又麻烦的要死.只要专心做界面就行了

**Comment by icespite** [comment]
> 免得每次打包.又麻烦的要死.只要专心做界面就行了

你可以试下这个，我对这部分做了修改。
https://github.com/icespite/FridaHooker

**Comment by wrlu** [comment]
做的不错，不过现在更大的问题是，在AOSP Build上面，su并没有开放给untrusted_app使用，所以这个东西能用的范畴就小了不少，只适合刷了magisk的机器，所以就不如使用magisk frida插件好些了。:)
